<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test_suite_1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ae0c3972-9af1-4658-9090-f236fdbfaa06</testSuiteGuid>
   <testCaseLink>
      <guid>1a05e0ba-6a6a-4156-b8af-e54499c90446</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/defect_11</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>676203d9-160e-45ff-875d-d444315229ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>788621d8-b26e-4561-bee1-e5aefd76c8d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>201c7117-91b1-4710-bd22-e8f5b06855f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9e5d7a12-1318-4927-a805-7489c6f9f9c1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test_case_1</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>88d48dc2-fac0-4d99-a095-13aed378298d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Test_case_2</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
