<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_YesNo</name>
   <tag></tag>
   <elementGuidId>2ab21b9f-ee75-41eb-9f08-a10e5d28e4e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-wrapper-full']/div/div/div/div/div/div[3]/div/div/div/form/div/div[2]/ul/li/div/div[3]/div[3]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col col-lg-9</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
															Yes
															No
														</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-wrapper-full&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;curriculam-block&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col col-sm-9&quot;]/div[@class=&quot;lach_dev resp-tab-content course_tab&quot;]/div[@class=&quot;slider_divsblocks&quot;]/div[@class=&quot;form-group&quot;]/form[@class=&quot;form-horizontal saveLabel&quot;]/div[@class=&quot;su_course_curriculam&quot;]/div[@class=&quot;su_course_curriculam_default&quot;]/ul[@class=&quot;clearfix&quot;]/li[@class=&quot;su_blue_curr&quot;]/div[@class=&quot;col col-lg-12&quot;]/div[@class=&quot;su_course_add_quiz_content su_course_add_content_form su_course_add_quiz_form&quot;]/div[@class=&quot;formrow&quot;]/div[@class=&quot;row-fluid&quot;]/div[@class=&quot;col col-lg-9&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-wrapper-full']/div/div/div/div/div/div[3]/div/div/div/form/div/div[2]/ul/li/div/div[3]/div[3]/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Section'])[1]/preceding::div[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
